executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --parsable
    --gpus={resources.gpus}
default-resources:
  - partition=highmemory
  - mem_mb=500000
  - gpus=0
set-resources:
    link:
        partition: week
        mem_mb: 250000
    sleap_track:
        partition: GPU
        mem_mb: 32000
        gpus: 1
    sleap_convert:
        partition: week
        mem_mb: 8000
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
keep-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
# conda-frontend: mamba