name: invision_analysis
channels:
  - defaults
dependencies:
  - bzip2==1.0.8
  - ca-certificates
  - lame==3.100
  - libcxx==16.0.6
  - libffi==3.4.4
  - libiconv==1.17
  - libopus==1.3.1
  - libtasn1==4.19.0
  - libunistring==0.9.10
  - ncurses==6.4
  - tzdata==2023c
  - x264==1!152.20180806
  - xz==5.4.5
  - zlib==1.2.13
  - gettext==0.21.1
  - gmp==6.3.0
  - libpng==1.6.39
  - libvpx==1.10.0
  - matplotlib
  - openh264==1.8.0
  - openssl
  - readline==8.2
  - tk==8.6.12
  - freetype==2.10.4
  - libidn2==2.3.4
  - nettle==3.7.3
  - sqlite==3.41.2
  - gnutls==3.6.15
  - python==3.11.5
  - ffmpeg==4.2.2
  - iniconfig==1.1.1
  - packaging==23.1
  - pluggy==1.0.0
  - setuptools==68.2.2
  - wheel==0.41.2
  - pip==23.3.1
  - pytest==7.4.0
  - ipykernel
  - pillow
  - trackpy
  - av
